---
title: "Academic and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Educational History 

  * Undergraduate Education: University of California, Berkeley 
    + Graduation Date: May 2022
    + Degree: Bachelor's Degree in Chemistry
      - Minor in Toxicology 
  
  
  * Post-Graduate Education: Columbia University, Mailman School of Public Health 
    + Graduation Date: expected May 2028 
    + Degree: Doctor of Philosophy Degree in Environmental Health Sciences 
    
### Research Experience 

  * Undergraduate Research Assistant in Bowles Agro-Ecology Lab, *University of California, Berkeley*
  * Laboratory Operations Manager in Bowles Agro-Ecology Lab, *University of California, Berkeley*
  * APHL-CDC Environmental Health Laboratory Fellow, *New Hampshire State Public Health Labs*  

### Download Resume and CV
 Please find my resume here (last updated July 2023): 
 <a href="resume_2023.docx" download>click to download</a>
 
 And, here is a copy of my more recently updated Curriculum Vitae (CV): 
 <a href="GVS CV.docx" download>click to download</a>
 
 
 