---
title: "Instacart Data Dashboard"
output: html_document
date: "2023-10-27"
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
data("instacart")

instacart = 
  instacart |> 
  as_tibble()
```

Make a plot that shows the number of items ordered in each aisle, limiting this to aisles with more than 10000 items ordered. 
```{r}
instacart |> 
  count(aisle) |> 
  filter(n > 10000) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> 
  plot_ly (x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```


```{r}
instacart |> 
  group_by(department) |>  
  summarize(n_aisle = n_distinct(aisle)) |> 
  plot_ly (x = ~department, y = ~n_aisle, color = ~department, type = "box", colors = "viridis")
```

